In [19]:
import pandas as pd
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [5]:
df = pd.read_csv("df.csv")
print(df.shape)
df = df.drop(["Unnamed: 0"], axis = 1)
df.columns.values[0] = 'label' # renaming first column to label (y)
df.head(3)

(10000, 786)


label    1    2    3    4    5    6    7    8    9  ...  775  776  777  \
0      0  255  255  255  255  255  255  255  255  255  ...  255  255  255   
1      0  255  255  255  255  255  255  255  255  255  ...  255  255  255   
2      0  255  255  255  255  255  255  255  255  255  ...  255  255  255   

   778  779  780  781  782  783  784  
0  255  255  255  255  255  255  255  
1  255  255  255  255  255  255  255  
2  255  255  255  255  255  255  255  

[3 rows x 785 columns]

In [7]:
X = df.iloc[:, 1:]
y = df['label']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [103]:
rfc = RandomForestClassifier(n_jobs=-1,
                             n_estimators=350,
                             max_depth = 35,
                             max_features = 28,
                             bootstrap = False)

In [104]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=35, max_features=28, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [105]:
rfc.score(X_test, y_test)

0.9316

In [106]:
rcf_predictions = rfc.predict(X_test) 
  
# model accuracy for X_test   
accuracy = rfc.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, rcf_predictions) 

In [107]:
print(accuracy)

0.9316


In [108]:
print(cm)

[[247   1   1   0   1   0   4   1   2   0]
 [  0 247   1   2   2   1   1   0   1   1]
 [  4   3 206   0   4   2   1   2   5   7]
 [  1   1   1 228   1   1   1   2   8   7]
 [  3   4   0   0 258   0   5   1   0   3]
 [  1   2   0   2   0 224   2   1   2   4]
 [  0   2   1   0   4   4 237   2   1   1]
 [  1   2   0   0   6   1   0 244   0   3]
 [  0   5   4   2   4   1   2   4 237   7]
 [  0   1   0   2   4   1   0   1   5 201]]


In [109]:
print(classification_report(y_test, rcf_predictions))

print("Training set score for RF: %f" % rfc.score(X_train , y_train))
print("Testing  set score for RF: %f" % rfc.score(X_test  , y_test ))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       257
           1       0.92      0.96      0.94       256
           2       0.96      0.88      0.92       234
           3       0.97      0.91      0.94       251
           4       0.91      0.94      0.92       274
           5       0.95      0.94      0.95       238
           6       0.94      0.94      0.94       252
           7       0.95      0.95      0.95       257
           8       0.91      0.89      0.90       266
           9       0.86      0.93      0.90       215

   micro avg       0.93      0.93      0.93      2500
   macro avg       0.93      0.93      0.93      2500
weighted avg       0.93      0.93      0.93      2500

Training set score for RF: 0.999467
Testing  set score for RF: 0.931600
